### ISSUE TITLE
hostname --all-ip-addresses not available on all hostname implementations

### ISSUE THREAD

**Issue by ghost** [s417-lama/mpitx#3]
mpitx retrieves a list of all ip addresses of a host by running `hostname --all-ip-addresses`.
Not all hostname implementations support this switch (for example see this issue of another software: https://github.com/HorlogeSkynet/archey4/issues/4)
I think there are at least two variants of hostname (debian and GNU) which differ slightly. The GNU variant on my machine for example does not support the switch `--all-ip-addresses`.

A quick fix I tried was changing `--all-ip-addresses` to `--ip-addresses`, which is supported by the debian and GNU variants but I am unsure if I broke something by doing this. It seemingly still works when I run my MPI program on two machines using mpitx.

**Comment by s417-lama** [comment]
Thank you for your investigation.
Seems like the `--all-ip-addresses` option is preferred if available, I implemented a fallback to the `ip a` command to retrieve the list of IP addresses.

I fixed this issue in this commit: https://github.com/s417-lama/mpitx/commit/0457e13f79fa07ba051173f2fb47d9f2fb6fef67
Could you check if the fixed version works in your environment?

**Comment by ghost** [comment]
The fix is working on my machine. Thank you!

mpitx is very helpful, thank you for creating it :)
